const estabelecimentos = [
  { nome: "4 Grapes", endereco: "C/Càceres, 14, Barcelona", cidade: "Barcelona" },
  { nome: "Abacus Cooperativa SCCL - Fabra i Puig", endereco: "P. Fabra i Puig, 196, Barcelona", cidade: "Barcelona" },
  { nome: "Abacus Urquinaona", endereco: "c/ Ausiàs Marc, 16, Barcelona", cidade: "Barcelona" },
  { nome: "Abracadabra Llibres", endereco: "C/ General Alvarez de Castro, 5, Barcelona", cidade: "Barcelona" },
  { nome: "Ada's store", endereco: "C. Comte Borrell, 95, Barcelona", cidade: "Barcelona" },
  { nome: "Adm. Loteria Poblenou", endereco: "C. Llull, 189, Barcelona", cidade: "Barcelona" },
  { nome: "Aguapur", endereco: "Rector Triadó, 15, Barcelona", cidade: "Barcelona" },
  { nome: "Al Gra del sac al plat", endereco: "Sant Cristòfol, 17, Barcelona", cidade: "Barcelona" },
  { nome: "Albert Calçats", endereco: "Dos de Maig, 221, A-22 bis, Barcelona", cidade: "Barcelona" },
  { nome: "Alcúdia", endereco: "Alcúdia, 50, Barcelona", cidade: "Barcelona" },
  { nome: "Al·lots", endereco: "Consell de Cent, 266, Barcelona", cidade: "Barcelona" },
  { nome: "Ampli-Art Marimón", endereco: "Ptge. Llívia, 33, Barcelona", cidade: "Barcelona" },
  { nome: "Àngel", endereco: "Passeig de Fabra i Puig, 270, Barcelona", cidade: "Barcelona" },
  { nome: "ANJU", endereco: "C. Pons i Gallarza, 5-7, local 4, Barcelona", cidade: "Barcelona" },
  { nome: "Arkham Còmics", endereco: "Carrer Xuclà, 16, local, Barcelona", cidade: "Barcelona" },
  { nome: "Armand Òptics", endereco: "Clot, 66, Barcelona", cidade: "Barcelona" },
  { nome: "Aromes Cafè Lounge", endereco: "c/ Gran de Sant Andreu, 152, Barcelona", cidade: "Barcelona" },
  { nome: "Art i Decoració", endereco: "Mineria, 17, botiga 1, Barcelona", cidade: "Barcelona" },
  { nome: "Artcants", endereco: "Mercat dels Encants, Carrer de los Castillejos, 158, Local 635-636, 08013 Barcelona, Barcelona", cidade: "Barcelona" },
  { nome: "Arxé Moda", endereco: "Pl. del Doctor Serrat, 3, Barcelona", cidade: "Barcelona" },
  { nome: "Assemblea Nacional Catalana", endereco: "C/Marina, 315, Barcelona", cidade: "Barcelona" },
  { nome: "Associació Cultural i Recreativa Juguem", endereco: "c. de Berenguer de Palou 64, Barcelona", cidade: "Barcelona" },
  { nome: "Associació Cultural i Social Bac de Roda", endereco: "Camí Antic de València. 96 - 116, Barcelona", cidade: "Barcelona" },
  { nome: "Associació cultural La Bibliomusicineteca", endereco: "C/Vila i Vilà, 76, Barcelona", cidade: "Barcelona" },
  { nome: "Associació de Ball Alocubano", endereco: "C. Joncar, 27, local 2, Barcelona", cidade: "Barcelona" },
  { nome: "Associació de Mestres Rosa Sensat", endereco: "Av. Drassanes,  3, Barcelona", cidade: "Barcelona" },
  { nome: "Associació de Veïnes i Veïns del Clot-Camp de l'Arpa", endereco: "C. Sibèlius, 3, Barcelona", cidade: "Barcelona" },
  { nome: "Associació Enxarxa. Pla Comunitari Besòs - Maresme", endereco: "Rambla Prim, 87 - 89, Barcelona", cidade: "Barcelona" },
  { nome: "Associació Musical Andreuenca", endereco: "c/ Capella, 14, Barcelona", cidade: "Barcelona" },
  { nome: "Associació sociocultural La Formiga", endereco: "Elkano, 74, baixos, Barcelona", cidade: "Barcelona" },
  { nome: "Associació Xarxa Dos Deu, per la Millora del Barri de la Sagrada Família", endereco: "Padilla, 210, baixos, Barcelona", cidade: "Barcelona" },
  { nome: "Ateneu Popular de les Corts", endereco: "Galileu, 252, Barcelona", cidade: "Barcelona" },
  { nome: "Atzavara Llibreria", endereco: "Escorial, 94, Barcelona", cidade: "Barcelona" },
  { nome: "Àudio Vídeo Tell", endereco: "C/ Guillem Tell, 36, Barcelona", cidade: "Barcelona" },
  { nome: "Aúpa Organics", endereco: "Rbla. del Poblenou, 66, Barcelona", cidade: "Barcelona" },
  { nome: "Auto-escuelas Batlle", endereco: "Passeig de Valldaura, 266, Barcelona", cidade: "Barcelona" },
  { nome: "Autòctons", endereco: "Rogent, 24, Barcelona", cidade: "Barcelona" },
  { nome: "Autoescola la Ele", endereco: "Rambla Prim, 83, Barcelona", cidade: "Barcelona" },
  { nome: "Azure", endereco: "c/ Gran de Sant Andreu, Barcelona", cidade: "Barcelona" },
  { nome: "BANBO TOYS", endereco: "Laforja, 77, Barcelona", cidade: "Barcelona" },
  { nome: "Bar Catalunya", endereco: "C. Pere IV, 120, Barcelona", cidade: "Barcelona" },
  { nome: "Bar El Xampinyonet. Mercat de Canyelles", endereco: "Antonio Machado, 10, Barcelona", cidade: "Barcelona" },
  { nome: "Bar Restaurant Núria Pous", endereco: "C. Santander, 16, Barcelona", cidade: "Barcelona" },
  { nome: "Bar-celona", endereco: "Sants, 308, Barcelona", cidade: "Barcelona" },
  { nome: "Bar-celona", endereco: "Vallespir, 81, Barcelona", cidade: "Barcelona" },
  { nome: "Barra/llibre", endereco: "Riego, 13, Barcelona", cidade: "Barcelona" },
  { nome: "Bateau Lune", endereco: "Plaça de la Virreina, 7, Barcelona", cidade: "Barcelona" },
  { nome: "Bell Estiu", endereco: "Verdi, 8, local 2, Barcelona", cidade: "Barcelona" },
  { nome: "Belles Arts Ferran SL", endereco: "C. Ferran, 39, local 2, Barcelona", cidade: "Barcelona" },
  { nome: "Biblioteca Gabriel García Márquez (Biblioteques de Barcelona)", endereco: "Plaça de Carmen Balcells Segalà, 1, Barcelona", cidade: "Barcelona" },
  { nome: "Blau intens", endereco: "c. Floridablanca, 64, Barcelona", cidade: "Barcelona" },
  { nome: "BO DE BO", endereco: "C. Sant Hermenegild, 7-9, Barcelona", cidade: "Barcelona" },
  { nome: "Bocí", endereco: "Via Augusta, 112, Barcelona", cidade: "Barcelona" },
  { nome: "Bolibloc", endereco: "C. Sant Quintí, 39, Barcelona", cidade: "Barcelona" },
  { nome: "Bona nit Matalasseria", endereco: "Rogent, 90, Barcelona", cidade: "Barcelona" },
  { nome: "Bracafè", endereco: "C. Comte d'Urgell, 35, Barcelona", cidade: "Barcelona" },
  { nome: "C. Art", endereco: "C. Menorca, 8-10, Barcelona", cidade: "Barcelona" },
  { nome: "Cake House", endereco: "Pl. Mañé i Flaquer, 4, Barcelona", cidade: "Barcelona" },
  { nome: "Cal Pueyo", endereco: "Vilamur, 20, Barcelona", cidade: "Barcelona" },
  { nome: "Calçats Arenillas", endereco: "Av. Riera de Cassoles, 15, Barcelona", cidade: "Barcelona" },
  { nome: "Calçats Toll", endereco: "Cabestany, 5, Barcelona", cidade: "Barcelona" },
  { nome: "Call", endereco: "c/ Gran de Sant Andreu, 265, Barcelona", cidade: "Barcelona" },
  { nome: "Cansaladeria Puig", endereco: "Gran de Sant Andreu, 147, Barcelona", cidade: "Barcelona" },
  { nome: "Cansaladeries Aldomà", endereco: "Mercat d'Hostafrancs, carrer Creu Coberta, 93, parada 169-198, Barcelona", cidade: "Barcelona" },
  { nome: "Carmen Decoración", endereco: "C. Bilbao, 33-35, local 12, Barcelona", cidade: "Barcelona" },
  { nome: "Carnisseria Ana Pilar", endereco: "Rambla Prim, 153, Barcelona", cidade: "Barcelona" },
  { nome: "Carnisseria Andreu", endereco: "Pl. Mercadal, 41 (mercat, p.11), Barcelona", cidade: "Barcelona" },
  { nome: "Carnisseria Marina", endereco: "c/ Tajo, 75 (mercat d'Horta parades 18-21), Barcelona", cidade: "Barcelona" },
  { nome: "Carnisseries Solé", endereco: "Mercat de les Corts, Travessera de les Corts, 215, parada 97-101, Barcelona", cidade: "Barcelona" },
  { nome: "Carns Banach", endereco: "Travessera de les Corts, 215, Barcelona", cidade: "Barcelona" },
  { nome: "Carns Batllori", endereco: "Mercat de la Barceloneta, parada 23-24, Barcelona", cidade: "Barcelona" },
  { nome: "Carns Gasull", endereco: "Mercat de Sants (carrer Sant Jordi, 6), Barcelona", cidade: "Barcelona" },
  { nome: "Carns Juan i Loli. Mercat de Canyelles", endereco: "Antonio Machado, 10, Barcelona", cidade: "Barcelona" },
  { nome: "Casa Carot", endereco: "C. Dagueria, 16, Barcelona", cidade: "Barcelona" },
  { nome: "Casa Rusca", endereco: "c/ Gran de Sant Andreu, 135, Barcelona", cidade: "Barcelona" },
  { nome: "Casa Vives, SL", endereco: "Sants, 74, Barcelona", cidade: "Barcelona" },
  { nome: "Casal Catòlic de Sant Andreu", endereco: "c. Pons i Gallarza, 58, Barcelona", cidade: "Barcelona" },
  { nome: "Casal de Barri Bac de Roda-Poblenou", endereco: "Camí Antic de València, 106, Barcelona", cidade: "Barcelona" },
  { nome: "Casal de Barri la Llacuna", endereco: "C. Bolívia, 49, Barcelona", cidade: "Barcelona" },
  { nome: "Casal de Barri la Palmera. Associació de veïns La Palmera Centre", endereco: "c/ de Duoda, 6 - 22, baixos, Barcelona", cidade: "Barcelona" },
  { nome: "Casal de Persones Grans Quatre Cantons", endereco: "Camí Antic de València, 116, baixos, Barcelona", cidade: "Barcelona" },
  { nome: "Cases Alcanar, pesca i tradició del Delta de l'Ebre", endereco: "c. Padilla, 266, Barcelona", cidade: "Barcelona" },
  { nome: "Castellers del Poble-sec", endereco: "C/ Blesa, 7, Barcelona", cidade: "Barcelona" },
  { nome: "Celler de Gelida", endereco: "Vallespir, 65, Barcelona", cidade: "Barcelona" },
  { nome: "Centre d'Interpretació dels Tres Tombs de Sant Andreu. Can Fontanet", endereco: "c. Sant Adrià, 20, Barcelona", cidade: "Barcelona" },
  { nome: "Centre de Teràpies Espai3om", endereco: "Pallars, 303-305, local 2, Barcelona", cidade: "Barcelona" },
  { nome: "Centre de Teràpies Sàlvia", endereco: "Ricart, 3, Barcelona", cidade: "Barcelona" },
  { nome: "Collita pròpia i ecològica Tugas i companyia. Mercat de Sant Andreu", endereco: "Plaça del Mercadal, 41 (Mercat de Sant Andreu, Parada 20), Barcelona", cidade: "Barcelona" },
  { nome: "Comercial Kare", endereco: "Pg. Valldaura, 239, Barcelona", cidade: "Barcelona" },
  { nome: "Confeccions El rellotge", endereco: "Comte Borrell, 89, Barcelona", cidade: "Barcelona" },
  { nome: "Coordinadora d'Entitats del Poblenou", endereco: "Rambla Poblenou, 49, Barcelona", cidade: "Barcelona" },
  { nome: "Coordinadora d'entitats Vern", endereco: "Carrer Santander 6, Barcelona", cidade: "Barcelona" },
  { nome: "Copy-Deas Copisteria", endereco: "C. Alfons el Magnànim, 47, Barcelona", cidade: "Barcelona" },
  { nome: "Corsetería Alfonsita", endereco: "Passeig de Fabra i Puig, 223, Barcelona", cidade: "Barcelona" },
  { nome: "Cupcakemoka Bakery", endereco: "c. del Llenguadoc, 92, Barcelona", cidade: "Barcelona" },
  { nome: "De Fang", endereco: "Berga, 12, Barcelona", cidade: "Barcelona" },
  { nome: "Del Be a la Manta", endereco: "Gran de Gràcia, 86, Barcelona", cidade: "Barcelona" },
  { nome: "Dietètica les Herbes. Mercat de Canyelles", endereco: "Antonio Machado, 10, Barcelona", cidade: "Barcelona" },
  { nome: "Dit i fet", endereco: "c/ Balari i Jovany, 4, Barcelona", cidade: "Barcelona" },
  { nome: "EBA Estudi de Belles Arts", endereco: "C. Agricultura, 225, Barcelona", cidade: "Barcelona" },
  { nome: "Edan Vedruna. Mercat de la Guineueta", endereco: "Pg Valldaura, 186, Barcelona", cidade: "Barcelona" },
  { nome: "EGE llibres i cosetes", endereco: "Benet Mercadé, 22, baixos, Barcelona", cidade: "Barcelona" },
  { nome: "El cau de la Naira", endereco: "Av. Rios de Janeiro, 75 local 2, Barcelona", cidade: "Barcelona" },
  { nome: "El cau de les herbes", endereco: "c/ Rosalia de Castro, 19, Barcelona", cidade: "Barcelona" },
  { nome: "El Celler de la Ribera", endereco: "Cigne, 12, baixos, Barcelona", cidade: "Barcelona" },
  { nome: "El Gat Pelut", endereco: "Caballero, 58, Barcelona", cidade: "Barcelona" },
  { nome: "El gat pirata", endereco: "Baixada de la Plana, 46, Barcelona", cidade: "Barcelona" },
  { nome: "El Món de la joguina", endereco: "C/ Mallorca, 190, Barcelona", cidade: "Barcelona" },
  { nome: "El pa sencer", endereco: "Vallespir, 161, Barcelona", cidade: "Barcelona" },
  { nome: "El racó de la Rosa", endereco: "c. Rocafort, 12, Barcelona", cidade: "Barcelona" },
  { nome: "El rei de la màgia", endereco: "c/Princesa, 11, Barcelona", cidade: "Barcelona" },
  { nome: "El Taller de la Raquel", endereco: "C/ La Gleva, 2, Barcelona", cidade: "Barcelona" },
  { nome: "El Taní vinològic SL", endereco: "Pl Virrei Amat, 12, Barcelona", cidade: "Barcelona" },
  { nome: "Electronuki", endereco: "Cristóbal de Moura, 209, Barcelona", cidade: "Barcelona" },
  { nome: "Els Titons de las Palmeras", endereco: "Gran Via de les Corts Catalanes, 837, Barcelona", cidade: "Barcelona" },
  { nome: "Endansa't", endereco: "Ter, 18, baixos 3a, Barcelona", cidade: "Barcelona" },
  { nome: "Escoda. Decoracions Alessandra", endereco: "C/ Joan Güell, 136, Barcelona", cidade: "Barcelona" },
  { nome: "Escofet Oliver", endereco: "Mallorca, 133-157, parades núm. 7, 8, 9, Barcelona", cidade: "Barcelona" },
  { nome: "Escola-Taller Novart", endereco: "Enamorats, 140, Barcelona", cidade: "Barcelona" },
  { nome: "Espai Abacus", endereco: "Enric Granados, 112, Barcelona", cidade: "Barcelona" },
  { nome: "Espai Mallorca", endereco: "Plaça Vicenç Martorell. 1, baixos, Barcelona", cidade: "Barcelona" },
  { nome: "Espaiflors", endereco: "Concili de Trento, 255-263, Barcelona", cidade: "Barcelona" },
  { nome: "Estanc Papereria Paloma", endereco: "C. Clot, 59, Barcelona", cidade: "Barcelona" },
  { nome: "Esther Voltà", endereco: "Gran Via de les Corts Catalanes, 274, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Àngels Escolà Marco", endereco: "Sant Roc, 26, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Avinyó", endereco: "C. Avinyó, 32, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Bonany Jané", endereco: "c/ Sant Antoni M. Claret, 97, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia de la Creu", endereco: "Avinyó, 27, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Diagonal 180", endereco: "Av. Diagonal, 180, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Domingo", endereco: "Salvà, 33, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Eulàlia Vives Ferrer", endereco: "C. Manso, 64, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Fortpienc", endereco: "Sardenya, 184, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Franquesa", endereco: "C. Gran de Sant Andreu, 260, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Garrofers", endereco: "Garrofers, 52, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Jaume Giró Loperena", endereco: "Marià Aguiló, 53, bxs, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia March Puigoriol", endereco: "C. Mallorca, 312, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Montse Villar", endereco: "Rambla Poblenou, 21, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Ortopèdia Bonaplata", endereco: "C. Bonaplata, 32, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Pascual Balañá Vives", endereco: "C. Comte Borrell, 43, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Pla Pastrana", endereco: "Alfons el Magnànim, 91, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Poblenou", endereco: "C. Pallars, 231, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Prim 74", endereco: "Rambla Prim, 74, Barcelona", cidade: "Barcelona" },
  { nome: "Farmàcia Raimon Piqué Figuerola", endereco: "C. Sant Carles, 7, Barcelona", cidade: "Barcelona" },
  { nome: "Fent Punt", endereco: "Gran Via Carles III, 46-48, Barcelona", cidade: "Barcelona" },
  { nome: "Ferreteria El Casal", endereco: "Passatge dels Garrofers, 29, Barcelona", cidade: "Barcelona" },
  { nome: "Flor de Lis", endereco: "Cigne, 15, Barcelona", cidade: "Barcelona" },
  { nome: "Floristeria Navarrete Pizarro, SL", endereco: "Carrer d'en Rull, 3, Barcelona", cidade: "Barcelona" },
  { nome: "Flors Dolors", endereco: "Mercat d'Hostafrancs, Creu Coberta, 93, Parada exterior núm. 86, Barcelona", cidade: "Barcelona" },
  { nome: "Flowrspace", endereco: "Garrofers, 36, Barcelona", cidade: "Barcelona" },
  { nome: "FNAC Glòries", endereco: "Av. Diagonal, 208, Barcelona", cidade: "Barcelona" },
  { nome: "Foment Martinenc", endereco: "Provença, 591-593, Barcelona", cidade: "Barcelona" },
  { nome: "Foment Sardanista Andreuenc", endereco: "c. Cuba, 2, Barcelona", cidade: "Barcelona" },
  { nome: "Formatges i mantegues Simó", endereco: "C/ Sant Pere Més Alt, 40, Barcelona", cidade: "Barcelona" },
  { nome: "Forn Elias", endereco: "C. Freser, 90, Barcelona", cidade: "Barcelona" },
  { nome: "Forn Santanach", endereco: "Rambla Poble Nou 98, Barcelona", cidade: "Barcelona" },
  { nome: "Forn Trinitat", endereco: "Plaça de la Trinitat, 14 / carrer Bartrina 52-54 08030, Barcelona", cidade: "Barcelona" },
  { nome: "Forners & Pastissers Puig", endereco: "c/ Àngel Marquès, 14-18 baixos, Barcelona", cidade: "Barcelona" },
  { nome: "Foto 100", endereco: "Rambla Prim, 100, Barcelona", cidade: "Barcelona" },
  { nome: "Foto Xavi", endereco: "Av. Mistral, 8, Barcelona", cidade: "Barcelona" },
  { nome: "Fruct Select. Mercat de la Guineueta", endereco: "Pg Valldaura, 186, Barcelona", cidade: "Barcelona" },
  { nome: "Fruiteria El Tros", endereco: ", Barcelona", cidade: "Barcelona" },
  { nome: "Fruites i verdures Lluís Macià", endereco: "Mallorca, 133-157, parades núm. 50, 74, 75, Barcelona", cidade: "Barcelona" },
  { nome: "Fruites i verdures Maria", endereco: "Francesc Cambó, s/n (Mercat Santa Caterina), Barcelona", cidade: "Barcelona" },
  { nome: "Fruites i verdures Oms", endereco: "Mercat de les Corts, Travessera de les Corts, 215, parada 46-48, Barcelona", cidade: "Barcelona" },
  { nome: "Fruites Víctor. Mercat de la Guineueta", endereco: "Pg Valldaura, 186, Barcelona", cidade: "Barcelona" },
  { nome: "Fruits Dador", endereco: "Casp, 137, Barcelona", cidade: "Barcelona" },
  { nome: "Fruits secs Roser", endereco: "C/Creu Coberta, 93, Barcelona", cidade: "Barcelona" },
  { nome: "Fundació Privada Orfeó Martinenc", endereco: "Avinguda Meridiana 97, Barcelona", cidade: "Barcelona" },
  { nome: "Fustacadabra", endereco: "Joan Güell, 131, Barcelona", cidade: "Barcelona" },
  { nome: "Gadial", endereco: "Ronda Sant pau, 65, Barcelona", cidade: "Barcelona" },
  { nome: "Games Freak", endereco: "C. Sèquia Comtal, 5, Barcelona", cidade: "Barcelona" },
  { nome: "Gasca Moda Home", endereco: "Tamarit, 169, Barcelona", cidade: "Barcelona" },
  { nome: "Gèneres de punt La Torre", endereco: "Pl. Universitat, 4, Barcelona", cidade: "Barcelona" },
  { nome: "Ginkgo Llar", endereco: "C. Marià Aguiló, 59, Barcelona", cidade: "Barcelona" },
  { nome: "Gloria Vila", endereco: "Passeig de Fabra i Puig, 270,, Barcelona", cidade: "Barcelona" },
  { nome: "Gos i Gat", endereco: "Rogent, 16, Barcelona", cidade: "Barcelona" },
  { nome: "Granarium", endereco: "c. Ribes, 24, Barcelona", cidade: "Barcelona" },
  { nome: "Graneria Sant Andreu", endereco: "c. Gran de Sant Andreu, 29, Barcelona", cidade: "Barcelona" },
  { nome: "Guido Articles de Pell i Viatge", endereco: "Carrer Ferran, 14, Barcelona", cidade: "Barcelona" },
  { nome: "Guitart & Gust, plats preparats i llegums. Mercat de la Guineueta", endereco: "Pg Valldaura, 186, Barcelona", cidade: "Barcelona" },
  { nome: "Halcon viatges", endereco: "c. Manso, 74, Barcelona", cidade: "Barcelona" },
  { nome: "Handsel & Granel", endereco: "Av. Riera de Cassoles, 13, Barcelona", cidade: "Barcelona" },
  { nome: "Herbes i Mel dietètica Glòria", endereco: "c/Tajo, 75 (mercat d'Horta parada 68-89), Barcelona", cidade: "Barcelona" },
  { nome: "Herbolari Milfulles", endereco: "C. Agricultura, 252, local 1, Barcelona", cidade: "Barcelona" },
  { nome: "Herboristeria Margarida Castaño", endereco: "Lepant, 172, Barcelona", cidade: "Barcelona" },
  { nome: "Idem Art Gràfic", endereco: "C. Marià Aguiló, 24, Barcelona", cidade: "Barcelona" },
  { nome: "Idiomarum", endereco: "C. Sepúlveda, 145, Barcelona", cidade: "Barcelona" },
  { nome: "Idiomes Tarradellas", endereco: "Av. Josep Tarradellas, 96, Barcelona", cidade: "Barcelona" },
  { nome: "Idoni - Bon cor", endereco: "Avinguda Mistral, 20 bis, Barcelona", cidade: "Barcelona" },
  { nome: "Idyllica", endereco: "Rambla de Prat, 11, Barcelona", cidade: "Barcelona" },
  { nome: "Il·luminació Can Corretja", endereco: "Pere Pau, 2, Barcelona", cidade: "Barcelona" },
  { nome: "In Blue", endereco: "Travessera de les Corts, 300, Barcelona", cidade: "Barcelona" },
  { nome: "Index Books", endereco: "Melcior de Palau, 145, Barcelona", cidade: "Barcelona" },
  { nome: "Invictus Nutrició & Fitness", endereco: "Rogent, 3, Barcelona", cidade: "Barcelona" },
  { nome: "IPB Dental", endereco: "C. Puigcerdà, 289, Barcelona", cidade: "Barcelona" },
  { nome: "Isabel", endereco: "Plaça La Font, s/n, parada 7 exterior, Barcelona", cidade: "Barcelona" },
  { nome: "Isidro Cosmetic Shop", endereco: "C. Marià Aguiló, 83, baixos, Barcelona", cidade: "Barcelona" },
  { nome: "Joguines i regals Moliné", endereco: "plaça Eivissa, 6 (galeries Horta, botiga número 3), Barcelona", cidade: "Barcelona" },
  { nome: "Joguines La Rosalia", endereco: "Gran Via de les Corts Catalanes, 431, Barcelona", cidade: "Barcelona" },
  { nome: "Jugarxjugar", endereco: "Av. Gaudí, 39, Barcelona", cidade: "Barcelona" },
  { nome: "Juguetes Morera", endereco: "C/ Riera Alta, 2, Barcelona", cidade: "Barcelona" },
  { nome: "Juguijuga", endereco: "Passeig Sant Joan, 35, baixos, Barcelona", cidade: "Barcelona" },
  { nome: "Júlia Fruites i Verdures", endereco: "Mercat de Sants (carrer Sant Jordi, 6), Barcelona", cidade: "Barcelona" },
  { nome: "Karnipolis. Mercat de la Guineueta", endereco: "Pg Valldaura, 186, Barcelona", cidade: "Barcelona" },
  { nome: "Kata", endereco: "C. Pujades, 316, Barcelona", cidade: "Barcelona" },
  { nome: "L'estanc del carrer Blai", endereco: "carrer Blai, 1, Barcelona", cidade: "Barcelona" },
  { nome: "L'herbolari", endereco: "c. Rocafort, 50, Barcelona", cidade: "Barcelona" },
  { nome: "L'Herbolari de Casp", endereco: "c. Casp, 139 - local 4, Barcelona", cidade: "Barcelona" },
  { nome: "L'Hortet Seleccions", endereco: "Sanpere i Miquel, 39, local, Barcelona", cidade: "Barcelona" },
  { nome: "LA BACANAL - BARCELONA", endereco: "Av. Riera de Cassoles, 11, Barcelona", cidade: "Barcelona" },
  { nome: "La Bodegueta del Guinardó", endereco: "c/Varsòvia, 84, Barcelona", cidade: "Barcelona" },
  { nome: "La botiga de la Pepi", endereco: "c. Mercat, 4, Barcelona", cidade: "Barcelona" },
  { nome: "La caixa d'eines", endereco: "Aragó, 367, Barcelona", cidade: "Barcelona" },
  { nome: "La Carbonera", endereco: "Blai, 40, Barcelona", cidade: "Barcelona" },
  { nome: "La carn de la Noe", endereco: "c/Creu Coberta, 93, Barcelona", cidade: "Barcelona" },
  { nome: "La Conxita", endereco: "Vallespir, 59, Barcelona", cidade: "Barcelona" },
  { nome: "La deessa del bosc", endereco: "C. Manso, 34, Barcelona", cidade: "Barcelona" },
  { nome: "La Farinera Ateneu del Clot", endereco: "c/ Muntanya, 16 BIS, Barcelona", cidade: "Barcelona" },
  { nome: "La font de mimir", endereco: "Costa i Cuxart, 5, Barcelona", cidade: "Barcelona" },
  { nome: "La Girella", endereco: "c/ Santa Carolina, 48, Barcelona", cidade: "Barcelona" },
  { nome: "La Jungla", endereco: "Pl. Sant Bernat Calbó, 8, Barcelona", cidade: "Barcelona" },
  { nome: "La licorera del Poblenou", endereco: "Taulet, 91, Barcelona", cidade: "Barcelona" },
  { nome: "La Llama Store", endereco: "Tamarit, 148, Barcelona", cidade: "Barcelona" },
  { nome: "La mamavaca", endereco: "Rambla de Prat, 25, Barcelona", cidade: "Barcelona" },
  { nome: "La Maquinària", endereco: "C. de Llenguadoc 82, Barcelona", cidade: "Barcelona" },
  { nome: "La Marga Moda Infantil", endereco: "Av. De la Mare de Déu de Montserrat, 113, Barcelona", cidade: "Barcelona" },
  { nome: "La Merceria", endereco: "Villarroel, 221, Barcelona", cidade: "Barcelona" },
  { nome: "La Papereria J.R.", endereco: "Av. de la Riera de Cassoles, 9, Barcelona", cidade: "Barcelona" },
  { nome: "La pera", endereco: "Mercat de les Corts, parada 80-85, Travessera de les Corts, 215, Barcelona, Barcelona", cidade: "Barcelona" },
  { nome: "La Piccola Llibreria Italiana", endereco: "Pl. Sant Vicenç de Sarrià, 2, Barcelona", cidade: "Barcelona" },
  { nome: "La ragatzza. Mercat de la Guineueta", endereco: "Pg Valldaura, 186, Barcelona", cidade: "Barcelona" },
  { nome: "La Tenda de la Natura", endereco: "C. Comte Borrell, 81, Barcelona", cidade: "Barcelona" },
  { nome: "La Troballa", endereco: "C. Ample, 3, Barcelona", cidade: "Barcelona" },
  { nome: "Labossa", endereco: "Baixada del Mercat, 3, Barcelona", cidade: "Barcelona" },
  { nome: "Le Pain d'Éric & Benjamin", endereco: "C. Cardenal Vives i Tutó, 60, Barcelona", cidade: "Barcelona" },
  { nome: "Le Petit", endereco: "Calàbria, 136, Barcelona", cidade: "Barcelona" },
  { nome: "Lemon Printers", endereco: "Portbou, 30, Barcelona", cidade: "Barcelona" },
  { nome: "Les Cosines", endereco: "Rosa Puig-Rodon Pla (antic Santa Rosa), 14 bis, Barcelona", cidade: "Barcelona" },
  { nome: "Les ocasions", endereco: "C. Sant Carles, 10, Barcelona", cidade: "Barcelona" },
  { nome: "Llegits", endereco: "Sants, 162, Barcelona", cidade: "Barcelona" },
  { nome: "Llegums Porta-Novau", endereco: "Mallorca, 133-157, parades núm. 31-32, Barcelona", cidade: "Barcelona" },
  { nome: "Llenceria Maria", endereco: "Ajuntament, 5, Barcelona", cidade: "Barcelona" },
  { nome: "Llet crua", endereco: "C/Càceres, 14, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria A Peu de Pàgina", endereco: "C/ Major de Sarrià, 50, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Abadia", endereco: "Ausiàs March, 92, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Ça Porta", endereco: "C. Sant Pere Més Alt, 20, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Calders", endereco: "Passatge de Pere Calders, 9, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Canales", endereco: "Rbla. Fabra i Puig, 3, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria de la Imatge", endereco: "Sepúlveda, 87, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Documenta", endereco: "Pau Claris, 144, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Etcètera", endereco: "c/ Llull, 203, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Fabre", endereco: "Aribau, 84, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Fahrenheit 451", endereco: "C. de la Ribera, 8, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Finestres", endereco: "Diputació, 249, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria La Memòria", endereco: "Plaça de la Vila de Gràcia, 19, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria La Ploma", endereco: "c/ Sicília, 332, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Lesseps", endereco: "Pl. Lesseps, 31, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Papereria La Bosch", endereco: "Passeig de Maragall, 166, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Papereria Torradas", endereco: "Manso, 62, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Pebre Negre, SCCL", endereco: "Carrer Clot, 41, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Prole", endereco: "Comte Borrell, 100, Barcelona", cidade: "Barcelona" },
  { nome: "Llibreria Santos Ochoa (Flamma Tea SL)", endereco: "P. Fabra i Puig, 165, Barcelona", cidade: "Barcelona" },
  { nome: "Lluna de Formatge", endereco: "c. Ajuntament, 12, Barcelona", cidade: "Barcelona" },
  { nome: "Lluna de paper", endereco: "Feliu i Codina, 6, Barcelona", cidade: "Barcelona" },
  { nome: "Londji", endereco: "londjiborn@gmail.com, Barcelona", cidade: "Barcelona" },
  { nome: "Lusajo Esports SL", endereco: "Rbla Fabra i Puig, 47, Barcelona", cidade: "Barcelona" },
  { nome: "Mamá Heladera", endereco: "Rbla. Poblenou, 44, Barcelona", cidade: "Barcelona" },
  { nome: "Manuka Llenceria", endereco: "Rambla Guipúscoa, 6, Barcelona", cidade: "Barcelona" },
  { nome: "Marisc Vilaespasa", endereco: "C/Hostafrancs, 93, Barcelona", cidade: "Barcelona" },
  { nome: "Masclans Artesans del Bacallà", endereco: "Mercat de les Corts, Travessera de les Corts, parada 87-89, Barcelona", cidade: "Barcelona" },
  { nome: "Matalasseria A. Mercader", endereco: "C. Alfons XII, 81, Barcelona", cidade: "Barcelona" },
  { nome: "Matalasseria Lázaro", endereco: "Gran de Sant Andreu, 184, Barcelona", cidade: "Barcelona" },
  { nome: "Mathom", endereco: "C/ del Pi, 1, Barcelona", cidade: "Barcelona" },
  { nome: "MCM Fruites i Verdures", endereco: "Mallorca, 133-157, parada núm. 64, 65, Barcelona", cidade: "Barcelona" },
  { nome: "Menuts Lídia", endereco: "Plaça Font, s/n (Mercat de la Barceloneta, parada 51-53), Barcelona", cidade: "Barcelona" },
  { nome: "Mercè del Prat", endereco: "C/Creu Coberta, 93, Barcelona", cidade: "Barcelona" },
  { nome: "Merceria Barceloneta", endereco: "Plaça la Font, s/n  (parada exterior Mercat Barceloneta 4-6), Barcelona", cidade: "Barcelona" },
  { nome: "Merceria Esmar", endereco: "C/ Entença, 122, Barcelona", cidade: "Barcelona" },
  { nome: "Merceria Perelló", endereco: "c. Gran de Sant Andreu, 261, Barcelona", cidade: "Barcelona" },
  { nome: "Merceria Rosa", endereco: "Rambla Guipúscoa, 4, Barcelona", cidade: "Barcelona" },
  { nome: "Miret", endereco: "C. Petritxol, 6, Barcelona", cidade: "Barcelona" },
  { nome: "Mobiliari Miralles", endereco: "C. Tamarit, 147, Barcelona", cidade: "Barcelona" },
  { nome: "Mobles Artesania", endereco: "Artesania, 56, Barcelona", cidade: "Barcelona" },
  { nome: "Modas Casas. Mercat de Canyelles", endereco: "Antonio Machado, 10, Barcelona", cidade: "Barcelona" },
  { nome: "Momments", endereco: "Carrer dels Comtes de Bell-lloc, 80, Barcelona", cidade: "Barcelona" },
  { nome: "Mònica Alba", endereco: "Sant Antoni M. Claret, 65, Barcelona", cidade: "Barcelona" },
  { nome: "Mr. Brown Store", endereco: "Carrer de Marià Aguiló, 82, Barcelona", cidade: "Barcelona" },
  { nome: "Nadons i mamis", endereco: "C/Sant Medir, 4, Barcelona", cidade: "Barcelona" },
  { nome: "Nap Buf", endereco: "C/ Santaló, 51, Barcelona", cidade: "Barcelona" },
  { nome: "Naturalment. Mercat de la Guineueta", endereco: "Pg. Valldaura, 186, Barcelona", cidade: "Barcelona" },
  { nome: "NATURASI MANDUCA", endereco: "c. Garcilaso, 191, Barcelona", cidade: "Barcelona" },
  { nome: "Niwa Cafeteria", endereco: "C. Vallirana, 78, Barcelona", cidade: "Barcelona" },
  { nome: "Noemí", endereco: "Plaça la Font, s/n, Barcelona", cidade: "Barcelona" },
  { nome: "Només planxa", endereco: "Sant Antoni M. Claret, 81, bis, Barcelona", cidade: "Barcelona" },
  { nome: "Normafilms", endereco: "Trav. de les Corts, 261, Barcelona", cidade: "Barcelona" },
  { nome: "Nou Celler Puigcerdà", endereco: "C. Puigcerdà, 272, Barcelona", cidade: "Barcelona" },
  { nome: "Oh Oh Andrea", endereco: "Mercat de Sants- parada ext. 4, Barcelona", cidade: "Barcelona" },
  { nome: "Ona Llibres", endereco: "Pau Claris, 94, Barcelona", cidade: "Barcelona" },
  { nome: "Onix BCN Perruqueria Vegana", endereco: "c. de Nadal, 31, Barcelona", cidade: "Barcelona" },
  { nome: "Òptica de Mercat", endereco: "C. Tamarit, 149, Barcelona", cidade: "Barcelona" },
  { nome: "Òptica Lago", endereco: "carrer Xavier Nogués, 41, Barcelona", cidade: "Barcelona" },
  { nome: "Òptica Marcos", endereco: "C. Tamarit, 156, Barcelona", cidade: "Barcelona" },
  { nome: "Òptica Poblenou", endereco: "c. Marià Aguiló, 88, Barcelona", cidade: "Barcelona" },
  { nome: "Opticalia Sant Andreu", endereco: "Carrer Gran de Sant Andreu, 414, Barcelona", cidade: "Barcelona" },
  { nome: "Ortopèdia Clot SL", endereco: "C. Clot, 82, Barcelona", cidade: "Barcelona" },
  { nome: "Orxateria, Gelateria Mallorca", endereco: "C. Mallorca, 620, Barcelona", cidade: "Barcelona" },
  { nome: "Ous Susana", endereco: "c/Tajo, 75 (mercat d'Horta parada 72-73), Barcelona", cidade: "Barcelona" },
  { nome: "Papereria 1000 Fulls", endereco: "C. Cantàbria, 22, local 4, Barcelona", cidade: "Barcelona" },
  { nome: "Papereria Canut", endereco: "C/ Girona, 73, Barcelona", cidade: "Barcelona" },
  { nome: "Papereria L'Amistat", endereco: "C. Amistat, 7, Barcelona", cidade: "Barcelona" },
  { nome: "Papereria Llibreria Eivissa s.c.p", endereco: "Plaça Eivissa, 7, Barcelona", cidade: "Barcelona" },
  { nome: "Papereria llibreria Nitus", endereco: "Blai, 6, Barcelona", cidade: "Barcelona" },
  { nome: "Papereria Nu&Ca", endereco: "Roser, 5, Barcelona", cidade: "Barcelona" },
  { nome: "Papereria Zygaena", endereco: "C. Sant Fructuós, 10, Barcelona", cidade: "Barcelona" },
  { nome: "Pastisseria Bonastre", endereco: "Tamarit, 136, Barcelona", cidade: "Barcelona" },
  { nome: "Pastisseria Confiteria La Palma", endereco: "Clot, 68-74, Barcelona", cidade: "Barcelona" },
  { nome: "Pastisseria Guifré", endereco: "Rambla del Poblenou, 71, Barcelona", cidade: "Barcelona" },
  { nome: "Pastisseria La perla de Sant Gervasi", endereco: "C. de les Santjoanistes, 6, Barcelona", cidade: "Barcelona" },
  { nome: "Pastisseria Sant Lluís", endereco: "C. Agricultura, 242, Barcelona", cidade: "Barcelona" },
  { nome: "Peix de proximitat la Barqueta", endereco: "Mercat de les Corts, Travessera de les Corts, 215, parada 105-108, Barcelona", cidade: "Barcelona" },
  { nome: "Peix i Marisc Montse i Sònia", endereco: "Mercat de la Barceloneta, parada 48-50, Barcelona", cidade: "Barcelona" },
  { nome: "Peix i marisc Neus. Mercat de la Guineueta", endereco: "Pg Valldaura, 186, Barcelona", cidade: "Barcelona" },
  { nome: "Peixateria Marisqueria La Mar de Fresc", endereco: "c/Tajo, 75 (mercat d'Horta- parada 140, 141, 142), Barcelona", cidade: "Barcelona" },
  { nome: "Peixateria Mary", endereco: "Mallorca, 133-157, parada núm. 72, Barcelona", cidade: "Barcelona" },
  { nome: "Peixateria Olga", endereco: "C/ Llobregós 147 (mercat del Carmel, parades 23-24-26-28), Barcelona", cidade: "Barcelona" },
  { nome: "Peixateria Ribera", endereco: "Mallorca, 133-157, parades núm. 10, 11, Barcelona", cidade: "Barcelona" },
  { nome: "Peixos Jack", endereco: "C. Jaume Huguet, 38 (Mercat Besòs), Barcelona", cidade: "Barcelona" },
  { nome: "Peixos Martí", endereco: "C/Creu Coberta, 93, Barcelona", cidade: "Barcelona" },
  { nome: "Peixos Roqueta. Mercat de Canyelles", endereco: "Antonio Machado, 10, Barcelona", cidade: "Barcelona" },
  { nome: "Perdins", endereco: "c/ Sant Antoni Ma Claret, 139, Barcelona", cidade: "Barcelona" },
  { nome: "Perruqueria Binèfar", endereco: "Binèfar, 4 (botiga 2), Barcelona", cidade: "Barcelona" },
  { nome: "Petit gegant", endereco: "Parlament, 6, Barcelona", cidade: "Barcelona" },
  { nome: "Piacci Argent", endereco: "Plaça del Comerç, 3, Barcelona", cidade: "Barcelona" },
  { nome: "Poblenou Digital", endereco: "No té adreça física, Barcelona", cidade: "Barcelona" },
  { nome: "Pollastres & altres Siscu. Mercat de la Guineueta", endereco: "Pg. Valldaura, 186, Barcelona", cidade: "Barcelona" },
  { nome: "Polleria Caça Francesc", endereco: "Mercat de la Barceloneta, parada 27-28, Barcelona", cidade: "Barcelona" },
  { nome: "Polleria Eulàlia. Mercat de Sant Andreu", endereco: "Mercat de Sant Andreu, parades 21-22. Pl. Mercadal, 41, Barcelona", cidade: "Barcelona" },
  { nome: "Rellotgeria J. Buetas", endereco: "C. Camp Arriassa, 81 (entrada per Rbla. Prim), Barcelona", cidade: "Barcelona" },
  { nome: "Reparat Millor que Nou", endereco: "C. Sepúlveda, 45-47, baixos, Barcelona", cidade: "Barcelona" },
  { nome: "Rocafort Modelisme SL", endereco: "Gran Via de les Corts Catalanes, 436, Barcelona", cidade: "Barcelona" },
  { nome: "Roldan Joiers", endereco: "C/Blai, 16, Barcelona", cidade: "Barcelona" },
  { nome: "Sabateca", endereco: "c. Gran de Sant Andreu, 208, Barcelona", cidade: "Barcelona" },
  { nome: "Sagitari Llibres", endereco: "Passatge Vila i Rosell, 10, Barcelona", cidade: "Barcelona" },
  { nome: "Salados Funes. Mercat de la Guineueta", endereco: "Pg Valldaura, 186, Barcelona", cidade: "Barcelona" },
  { nome: "Saló de Bellesa Rubel", endereco: "Rambla Prim, 98, Barcelona", cidade: "Barcelona" },
  { nome: "Sanitas Poblenou", endereco: "Bilbao, 83, Barcelona", cidade: "Barcelona" },
  { nome: "Santa Antònia", endereco: "Creu Coberta, 99, Barcelona", cidade: "Barcelona" },
  { nome: "SAT! Sant Andreu Teatre", endereco: "c. Neopàtria, 54, Barcelona", cidade: "Barcelona" },
  { nome: "Sendak", endereco: "Còrsega, 461, Barcelona", cidade: "Barcelona" },
  { nome: "Several Cafè", endereco: "c/ Gran de Sant Andreu, 165, Barcelona", cidade: "Barcelona" },
  { nome: "Siente", endereco: "Rogent, 96, Barcelona", cidade: "Barcelona" },
  { nome: "Societat Cultural i Esportiva La Lira", endereco: "C. Coroleu, 15, Barcelona", cidade: "Barcelona" },
  { nome: "Sol Nature", endereco: "Plaça de la Llibertat, 13, Barcelona", cidade: "Barcelona" },
  { nome: "Sol&Deco", endereco: "Passeig Maragall, 178-180 Local 3, Barcelona", cidade: "Barcelona" },
  { nome: "STENCIL BARCELONA", endereco: "Av. de la Riera de Cassoles, 11, Barcelona", cidade: "Barcelona" },
  { nome: "Sunta. Professionals del peix", endereco: "Mercat de les Corts, Travessera de les Corts, 215, Barcelona", cidade: "Barcelona" },
  { nome: "Tarruella", endereco: "Passeig de Fabra i Puig, 270, Barcelona", cidade: "Barcelona" },
  { nome: "Taula i cuina", endereco: "C. Tamarit, 162, Barcelona", cidade: "Barcelona" },
  { nome: "Teixidó", endereco: "C. Marià Aguiló, 48, Barcelona", cidade: "Barcelona" },
  { nome: "Teixidó. Tot per a la llar", endereco: "Provença, 474, Barcelona", cidade: "Barcelona" },
  { nome: "Teixits Irelena", endereco: "P. Fabra i Puig, 248, Barcelona", cidade: "Barcelona" },
  { nome: "Teixits Pàdua", endereco: "Sant Jordi, 13, Barcelona", cidade: "Barcelona" },
  { nome: "Tempo", endereco: "C. Calàbria, 62, Barcelona", cidade: "Barcelona" },
  { nome: "Terra de salut", endereco: "Blesa, 45, Barcelona", cidade: "Barcelona" },
  { nome: "Terranova 80", endereco: "C/Segre, 55, local 1 bis, Barcelona", cidade: "Barcelona" },
  { nome: "Tito Fresh Fruit", endereco: "Plaça Regomir, 1, Barcelona", cidade: "Barcelona" },
  { nome: "Tocineria Els Nois", endereco: "C. Rogent, 132, Barcelona", cidade: "Barcelona" },
  { nome: "TOSSUDA STUDIO", endereco: "C. Vallirana, 63, local dret, Barcelona", cidade: "Barcelona" },
  { nome: "Totart", endereco: "Sants, 3, Barcelona", cidade: "Barcelona" },
  { nome: "Tradició peixatera", endereco: "c. Comte d'Urgell, 1 - parada 131 Mercat de Sant Antoni, Barcelona", cidade: "Barcelona" },
  { nome: "Vagi de gust SCP", endereco: "Mercat de les Corts, parada 70-71, Travessera de les Corts, 215, Barcelona", cidade: "Barcelona" },
  { nome: "Valls, Roba per la llar", endereco: "València, 542, A51, Barcelona", cidade: "Barcelona" },
  { nome: "Venivinum", endereco: "C/ de Còrsega, 209, Barcelona", cidade: "Barcelona" },
  { nome: "Verduleria BUBUB", endereco: "Carrer Joaquim Costa, 29, Barcelona", cidade: "Barcelona" },
  { nome: "Vestuari Compartit", endereco: "c/ Verdi, 100, Barcelona", cidade: "Barcelona" },
  { nome: "Via dolça", endereco: "c. Tamarit, 152, Barcelona", cidade: "Barcelona" },
  { nome: "Viatges Pons, SL", endereco: "Rubén Darío, 15, Barcelona", cidade: "Barcelona" },
  { nome: "Vom Fass", endereco: "Cigne, 14, Barcelona", cidade: "Barcelona" },
  { nome: "Xagrí", endereco: "Rbla. Poblenou, 77, Barcelona", cidade: "Barcelona" },
  { nome: "Xarcuteria Alfred Moliner", endereco: "Mallorca, 133-157, parades núm. 69, 70, Barcelona", cidade: "Barcelona" },
  { nome: "Xarcuteria Castelló", endereco: "Travessera de les Corts, 215. Mercat de les Corts, Barcelona", cidade: "Barcelona" },
  { nome: "Xarcuteria M. Guerrero. Mercat de la Guineueta", endereco: "Pg Valldaura, 186, Barcelona", cidade: "Barcelona" },
  { nome: "Xarcuteria Mireia. Mercat de Canyelles", endereco: "Antonio Machado, 10, Barcelona", cidade: "Barcelona" },
  { nome: "Xarcuteries Margarit Mercat de Sarrià", endereco: "Passeig Reina Elisenda, 8, Barcelona", cidade: "Barcelona" },
  { nome: "Xarcuters J. Tena", endereco: "Rambla del Poblenou, 89, Barcelona", cidade: "Barcelona" },
  { nome: "YOLANDA PUNT DE CREU", endereco: "AV. Riera de Cassoles, 15, Barcelona", cidade: "Barcelona" },
  { nome: "Zerovuit brewing SL", endereco: "C. Llacuna, 165, Barcelona", cidade: "Barcelona" },
];